#!/usr/bin/env bash
#
# ------------------------>% Thoth related content %<------------------------
#
THOTH_ASSEMBLE_DEBUG=${THOTH_ASSEMBLE_DEBUG:-0}
[[ ${THOTH_ASSEMBLE_DEBUG} -eq 0 ]] || set -e

# Submit stack to Thoth, but do not use the recommended one:
THOTH_DRY_RUN=${THOTH_DRY_RUN:-0}
# Force advises even if Pipfile.lock is present in the repo:
THOTH_ADVISE=${THOTH_ADVISE:-1}
# Use Thamos from git instead of a PyPI release:
THOTH_FROM_MASTER=${THOTH_FROM_MASTER:-0}
# Thoth host to submit recommendations to:
THOTH_HOST=${THOTH_HOST:-khemenu.thoth-station.ninja}
# Disable progressbar for thamos:
THAMOS_NO_PROGRESSBAR=${THAMOS_NO_PROGRESSBAR:-1}

# A directory where s2i places sources.
pushd /tmp/src

# Make a backup of the Pipfile.lock present in the git root.
[[ ${THOTH_DRY_RUN} -ne 0 && -f Pipfile.lock ]] && cp Pipfile.lock ../

[[ ( -f Pipfile && ! -f Pipfile.lock ) || ${THOTH_ADVISE} -ne 0 ]] && {
  echo "Updating pip and installing Thamos..."
  # Enable pip3.
  pip install --upgrade pip

  if [[ ${THOTH_FROM_MASTER} -eq 1 ]]; then
      pip3 install git+https://github.com/thoth-station/thamos
      pip3 install git+https://github.com/thoth-station/invectio
  else
      pip3 install thamos
  fi

  echo ">>> Performing hardware and software discovery..."
  thamos config --no-interactive
  echo ">>> Thoth's configuration file after hardware and software discovery:"
  cat .thoth.yaml
  echo ">>> Asking Thoth for advise..."
  if [[ ${THOTH_DRY_RUN} -ne 0 ]]; then
      thamos advise
  else
      thamos advise --no-wait
  fi
} || {
  echo "Thoth advises are not activated"
}

# Restore previous Pipfile.lock, do not use the original one on dry run.
[[ ${THOTH_DRY_RUN} -ne 0 ]] && {
    echo "Restoring previous Pipfile.lock as THOTH_DRY_RUN was set" >&2
    [[ ${THOTH_ASSEMBLE_DEBUG} -ne 0 ]] && cat Pipfile.lock || true
    [[ -f ../Pipfile.lock ]] && cp ../Pipfile.lock .
}

popd

# Uncomment if you want to use this script solely in an s2i as an extension:
#exec /usr/libexec/s2i/assemble
#
# ------------------------>% Thoth related content %<------------------------
#
